#include <iostream>
#include <fstream>
#include <string>
#include <cstdlib>
#include <limits>

using namespace std;

const int MAX_STUDENTS = 100;
const string FILENAME = "students.txt";

struct Student {
    string id;
    string name;
    float gpa;
};

Student students[MAX_STUDENTS]; 
int studentCount = 0; 


float calculateGPA(float obtained, float total) {
    float percentage = (obtained / total) * 100;

    if (percentage >= 85) return 4.0;
    if (percentage >= 80) return 3.7;
    if (percentage >= 75) return 3.3;
    if (percentage >= 70) return 3.0;
    if (percentage >= 65) return 2.7;
    if (percentage >= 60) return 2.3;
    if (percentage >= 55) return 2.0;
    if (percentage >= 50) return 1.7;
    return 0.0;
}


void loadData() {
    studentCount = 0;
    ifstream inFile(FILENAME);
    if (!inFile) return;

    while (studentCount < MAX_STUDENTS && inFile >> students[studentCount].id >> students[studentCount].name >> students[studentCount].gpa) {
        studentCount++;
    }
    inFile.close();
}

void rewriteFile() {
    ofstream outFile(FILENAME);
    if (outFile.is_open()) {
        for (int i = 0; i < studentCount; i++) {
            outFile << students[i].id << " " << students[i].name << " " << students[i].gpa << endl;
        }
        outFile.close();
    }
}

void appendToFile(const Student& s) {
    ofstream outFile(FILENAME, ios::app);
    if (outFile.is_open()) {
        outFile << s.id << " " << s.name << " " << s.gpa << endl;
        outFile.close();
    }
}

void generateReport() {
    system("cls");
    if (studentCount == 0) {
        cout << "No data to generate report.\n";
        return;
    }

    string reportName = "Final_Report.txt";
    ofstream report(reportName);

    if (report.is_open()) {
        report << "=================================================\n";
        report << "           UNIVERSITY OFFICIAL REPORT            \n";
        report << "=================================================\n\n";
        report << "Total Students: " << studentCount << "\n\n";

        report << "Roll No       Name                GPA     Status\n";
        report << "-------------------------------------------------\n";

        for (int i = 0; i < studentCount; i++) {
            string status = (students[i].gpa >= 2.0) ? "Pass" : "Fail";

            // Basic formatting for file
            report << students[i].id << "   "
                << students[i].name << "   \t"
                << students[i].gpa << "     "
                << status << endl;
        }
        report << "\n=================================================\n";
        report << "Generated by System.\n";

        report.close();
        cout << "\nSuccess! Report saved to '" << reportName << "'.\n";
    }
    else {
        cout << "Error creating report file.\n";
    }
}

void addStudent() {
    system("cls");
    if (studentCount >= MAX_STUDENTS) {
        cout << "Error: Database is full (Max " << MAX_STUDENTS << ").\n";
        return;
    }

    Student s;
    cout << "\n--- Add New Student ---\n";
    cout << "Enter Roll No (e.g., 2025-SE-450): ";
    cin >> s.id;

    // Check duplicate
    for (int i = 0; i < studentCount; i++) {
        if (students[i].id == s.id) {
            cout << "Error: Roll Number already exists!\n";
            return;
        }
    }

    cin.ignore();
    cout << "Enter Name: ";
    getline(cin, s.name);

    // Convert spaces to underscores
    for (int i = 0; i < s.name.length(); i++) {
        if (s.name[i] == ' ') s.name[i] = '_';
    }

    float marks[5];
    float totalObtained = 0;
    cout << "Enter marks for 5 subjects (0-100 only):\n";

    for (int i = 0; i < 5; i++) {
        while (true) {
            cout << "Subject " << i + 1 << ": ";
            cin >> marks[i];

            if (cin.fail()) {
                cin.clear();
                cin.ignore(numeric_limits<streamsize>::max(), '\n');
                cout << "Invalid input! Please enter a number.\n";
            }
            else if (marks[i] < 0 || marks[i] > 100) {
                cout << "Error: Marks must be between 0 and 100!\n";
            }
            else {
                break;
            }
        }
        totalObtained += marks[i];
    }

    s.gpa = calculateGPA(totalObtained, 500.0);

    students[studentCount] = s;
    studentCount++;

    appendToFile(s);

    cout << "\nSuccess: Student added and saved.\n";
    cout << "GPA: " << s.gpa << "\n";
}

void rankStudents() {
    system("cls");
    if (studentCount == 0) {
        cout << "\nNo records found.\n";
        return;
    }

    Student temp[MAX_STUDENTS];
    for (int i = 0; i < studentCount; i++) {
        temp[i] = students[i];
    }

    for (int i = 0; i < studentCount - 1; i++) {
        for (int j = 0; j < studentCount - i - 1; j++) {
            if (temp[j].gpa < temp[j + 1].gpa) {
                Student t = temp[j];
                temp[j] = temp[j + 1];
                temp[j + 1] = t;
            }
        }
    }


    cout << "\n--- STUDENT RANKINGS (By GPA) ---\n";
    cout << "Rank\tRoll No\t\tGPA\tName\n";
    cout << "------------------------------------------------\n";

    for (int i = 0; i < studentCount; i++) {
        cout << "#" << i + 1 << "\t"
            << temp[i].id << "\t"
            << temp[i].gpa << "\t"
            << temp[i].name << endl;
    }
}

void viewTopper() {
    system("cls");
    if (studentCount == 0) {
        cout << "\nNo records found.\n";
        return;
    }

    float maxGPA = -1.0;
    for (int i = 0; i < studentCount; i++) {
        if (students[i].gpa > maxGPA) maxGPA = students[i].gpa;
    }

    cout << "\n--- CLASS TOPPER(S) ---\n";
    for (int i = 0; i < studentCount; i++) {
        if (students[i].gpa == maxGPA) {
            cout << "Roll No: " << students[i].id << " | GPA: " << students[i].gpa << " | Name: " << students[i].name << endl;
        }
    }
}

void displayStudents() {
    system("cls");
    if (studentCount == 0) {
        cout << "\nNo records found.\n";
        return;
    }
    cout << "\n--- All Student Records ---\n";
    cout << "Roll No\t\tName\t\tGPA\n";
    cout << "----------------------------------------\n";
    for (int i = 0; i < studentCount; i++) {
        cout << students[i].id << "\t" << students[i].name << "\t\t" << students[i].gpa << endl;
    }
}

void searchStudent() {
    system("cls");
    string searchId;
    cout << "\n--- Search Student ---\n";
    cout << "Enter Roll No: ";
    cin >> searchId;

    bool found = false;
    for (int i = 0; i < studentCount; i++) {
        if (students[i].id == searchId) {
            cout << "\nFound: " << students[i].id << " | " << students[i].name << " | GPA: " << students[i].gpa << endl;
            found = true;
            break;
        }
    }
    if (!found) cout << "\nStudent not found.\n";
}

void updateStudent() {
    system("cls");
    string updateId;
    cout << "\n--- Update Student ---\n";
    cout << "Enter Roll No: ";
    cin >> updateId;

    bool found = false;
    for (int i = 0; i < studentCount; i++) {
        if (students[i].id == updateId) {
            cin.ignore();
            cout << "Enter New Name: ";
            getline(cin, students[i].name);
            for (int j = 0; j < students[i].name.length(); j++) {
                if (students[i].name[j] == ' ') students[i].name[j] = '_';
            }

            cout << "Enter New GPA: ";
            while (!(cin >> students[i].gpa) || students[i].gpa < 0 || students[i].gpa > 4.0) {
                cout << "Invalid GPA. Enter 0.0 - 4.0: ";
                cin.clear();
                cin.ignore(numeric_limits<streamsize>::max(), '\n');
            }

            rewriteFile();
            cout << "\nUpdated successfully.\n";
            found = true;
            break;
        }
    }
    if (!found) cout << "\nStudent not found.\n";
}

void deleteStudent() {
    system("cls");
    string deleteId;
    cout << "\n--- Delete Student ---\n";
    cout << "Enter Roll No: ";
    cin >> deleteId;

    bool found = false;
    for (int i = 0; i < studentCount; i++) {
        if (students[i].id == deleteId) {
            for (int j = i; j < studentCount - 1; j++) {
                students[j] = students[j + 1];
            }
            studentCount--;

            rewriteFile();
            cout << "\nDeleted successfully.\n";
            found = true;
            break;
        }
    }
    if (!found) cout << "\nStudent not found.\n";
}

int main() {
    loadData();

    int choice;
    while (true) {
        system("cls");
        cout << "\n=== University Management System ===\n";
        cout << "1. Add Student\n";
        cout << "2. Display All\n";
        cout << "3. Search Student\n";
        cout << "4. View Topper\n";
        cout << "5. Rank Students (Leaderboard)\n";
        cout << "6. Update Student\n";
        cout << "7. Delete Student\n";
        cout << "8. Generate Report (File)\n";
        cout << "9. Exit\n";
        cout << "Enter choice: ";

        cin >> choice;
        if (cin.fail()) {
            cin.clear();
            cin.ignore(numeric_limits<streamsize>::max(), '\n');
            cout << "\nInvalid input! Please enter a number.\n";
            system("pause");
            continue;
        }

        switch (choice) {
        case 1: addStudent(); break;
        case 2: displayStudents(); break;
        case 3: searchStudent(); break;
        case 4: viewTopper(); break;
        case 5: rankStudents(); break;
        case 6: updateStudent(); break;
        case 7: deleteStudent(); break;
        case 8: generateReport(); break;
        case 9: cout << "Exiting...\n"; return 0;
        default: cout << "Invalid choice!\n";
        }
        cout << "\n";
        system("pause");
    }

    return 0;
}